language: ruby
rvm: 2.0.0

branches:
  only:
    - develop
before_script:
  - git clone --quiet https://github.com/tamaxyo/test.git build
script:
  - bundle exec middleman build
after_script:
  - cd build
  - git add -A
  - git commit -m "Update"
  - '[ "$TRAVIS_BRANCH" == "develop" ] && [ $GH_TOKEN ] && git push --quiet https://$GH_TOKEN@github.com/tamaxyo/test.git master 2> /dev/null'

env:
  global:
    - GIT_COMMITER_NAME="tamaxyo"
    - GIT_COMMITER_EMAIL="tamaxyo@gmail.com"
    - GIT_AUTHOR_NAME="tamaxyo"
    - GIT_AUTHOR_EMAIL="tamaxyo@gmail.com"
secure: "B5qScFi1eKT9iwi3FLTwbI0CWm9NIqGbuZrtRHm4kcG7lLjaHsa7Sk4+UD3vlsNdtfZ2Kpv1MkZso8ML+C2Ca7Q9GzM9kwfXOzQMOj634rgGqLIhJqgsJYeXjV3F9xbdP2